import { Replay } from "../replay/DeterministicReplay";
import {
  MiniGameResult,
  MiniGameRunContext,
  StoryRuntimeSnapshot
} from "./ArcadeIntegrationTypes";
import { StoryEffect } from "./StoryTypes";

/**
 * Version identifier for ArcadeDebugRun serialized format.
 *
 * @public
 */
export const ARCADE_DEBUG_RUN_VERSION = 1;

/**
 * Complete, versioned debug run bundle recording an arcade session and its narrative impact.
 *
 * @public
 */
export interface ArcadeDebugRun {
  /** Schema version identifier for the debug run payload. */
  readonly version: number;
  /** Encounter ID associated with the run. */
  readonly encounterId: string;
  /** Full runtime context used to initialize the minigame. */
  readonly runContext: MiniGameRunContext;
  /** Initial story runtime snapshot recorded prior to starting the run. */
  readonly initialStorySnapshot: StoryRuntimeSnapshot;
  /** Complete input replay capturing all frames for deterministic playback. */
  readonly replay: Replay;
  /** Expected final minigame result achieved in the recording. */
  readonly expectedResult: MiniGameResult;
  /** IDs of outcome rules matched during outcome processing. */
  readonly matchedRuleIds: ReadonlyArray<string>;
  /** Story narrative effects generated by the run outcome. */
  readonly generatedEffects: ReadonlyArray<StoryEffect>;
}

/**
 * Utility functions for creating, serializing, deserializing, and validating ArcadeDebugRun bundles.
 *
 * @public
 */
export class ArcadeDebugRunManager {
  /**
   * Serializes an `ArcadeDebugRun` object into a JSON string.
   */
  public static serialize(debugRun: ArcadeDebugRun): string {
    return JSON.stringify(debugRun, null, 2);
  }

  /**
   * Deserializes and validates a JSON string into an `ArcadeDebugRun` object.
   *
   * @throws Error if version is unsupported or structure is invalid.
   */
  public static deserialize(jsonString: string): ArcadeDebugRun {
    const data = JSON.parse(jsonString);

    if (!data || typeof data !== "object") {
      throw new Error("[ArcadeDebugRunManager] Invalid JSON string payload.");
    }

    if (typeof data.version !== "number") {
      throw new Error("[ArcadeDebugRunManager] Missing version identifier in payload.");
    }

    if (data.version !== ARCADE_DEBUG_RUN_VERSION) {
      throw new Error(
        `[ArcadeDebugRunManager] Unsupported debug run version: ${data.version}. Expected ${ARCADE_DEBUG_RUN_VERSION}.`
      );
    }

    if (!data.encounterId || !data.runContext || !data.replay || !data.expectedResult) {
      throw new Error("[ArcadeDebugRunManager] Missing required fields in debug run payload.");
    }

    return data as ArcadeDebugRun;
  }
}
