import { StyleSheet } from "react-native";

export const NeonColors = {
  backgroundDeep: "#06060c",
  primaryCyan: "#00f0ff",
  pinkAsteroids: "#ff66cc",
  secondaryGreen: "#00ff66",
  white: "#ffffff",
  textSecondary: "#CCCCCC",
  textMuted: "#AAAAAA",
  highScoreGold: "#FFD700",
  inputBg: "#161622",
  overlayBg: "rgba(0, 0, 0, 0.75)",
};

export const sharedScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: NeonColors.backgroundDeep,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  startScreen: {
    flex: 1,
    backgroundColor: NeonColors.backgroundDeep,
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
  },
  title: {
    fontSize: 48,
    color: NeonColors.white,
    fontFamily: "monospace",
    fontWeight: "bold",
    marginBottom: 36,
    textAlign: "center",
    textShadowColor: NeonColors.primaryCyan,
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 16,
  },
  instructions: {
    fontSize: 16,
    color: NeonColors.textSecondary,
    fontFamily: "monospace",
    marginBottom: 12,
    textAlign: "center",
    paddingHorizontal: 20,
  },
  highScoreText: {
    fontSize: 20,
    color: NeonColors.highScoreGold,
    fontFamily: "monospace",
    marginBottom: 36,
  },
  startButton: {
    backgroundColor: NeonColors.white,
    paddingHorizontal: 32,
    paddingVertical: 16,
    borderRadius: 14,
    minWidth: 130,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: NeonColors.primaryCyan,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 12,
    elevation: 8,
  },
  multiButton: {
    backgroundColor: NeonColors.primaryCyan,
    paddingHorizontal: 32,
    paddingVertical: 16,
    borderRadius: 14,
    minWidth: 130,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: NeonColors.primaryCyan,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 12,
    elevation: 8,
  },
  startButtonText: {
    color: "#000000",
    fontSize: 20,
    fontWeight: "bold",
    fontFamily: "monospace",
  },
  multiButtonText: {
    color: "#000000",
    fontSize: 20,
    fontWeight: "bold",
    fontFamily: "monospace",
  },
  buttonRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  inputLabel: {
    color: NeonColors.primaryCyan,
    fontFamily: "monospace",
    fontSize: 14,
    fontWeight: "bold",
    marginBottom: 8,
    textAlign: "center",
    textTransform: "uppercase",
  },
  input: {
    backgroundColor: NeonColors.inputBg,
    color: NeonColors.white,
    padding: 15,
    borderRadius: 12,
    width: 260,
    marginBottom: 20,
    fontFamily: "monospace",
    textAlign: "center",
    fontSize: 18,
    borderWidth: 1,
    borderColor: "rgba(0, 240, 255, 0.2)",
  },
  backButton: {
    position: "absolute",
    top: 50,
    left: 20,
    zIndex: 100,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: NeonColors.primaryCyan,
    backgroundColor: "rgba(0, 240, 255, 0.15)",
    minHeight: 44,
    minWidth: 80,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  backButtonText: {
    color: NeonColors.primaryCyan,
    fontSize: 14,
    fontFamily: "monospace",
    fontWeight: "bold",
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: NeonColors.overlayBg,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
  },
  overlayText: {
    color: NeonColors.white,
    fontSize: 24,
    fontFamily: "monospace",
  },
});
