import { StyleSheet } from "react-native";
import { colors, spacing, typography, radius, effects } from "../theme";

export const NeonColors = {
  backgroundDeep: colors.background,
  primaryCyan: colors.cyan,
  pinkAsteroids: colors.pink,
  secondaryGreen: colors.green,
  white: colors.white,
  textSecondary: colors.textSecondary,
  textMuted: colors.textMuted,
  highScoreGold: colors.gold,
  inputBg: colors.surface,
  overlayBg: colors.overlay,
};

export const sharedScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  startScreen: {
    flex: 1,
    backgroundColor: colors.background,
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
  },
  title: {
    fontSize: typography.sizes.title,
    color: colors.white,
    fontFamily: typography.game,
    fontWeight: typography.weights.bold,
    marginBottom: spacing.xxxl,
    textAlign: "center",
    textShadowColor: colors.cyan,
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 16,
  },
  instructions: {
    fontSize: typography.sizes.md,
    color: colors.textSecondary,
    fontFamily: typography.game,
    marginBottom: spacing.md,
    textAlign: "center",
    paddingHorizontal: spacing.xl,
  },
  highScoreText: {
    fontSize: typography.sizes.xl,
    color: colors.gold,
    fontFamily: typography.game,
    marginBottom: spacing.xxxl,
  },
  startButton: {
    backgroundColor: colors.white,
    paddingHorizontal: spacing.xxxl,
    paddingVertical: spacing.lg,
    borderRadius: radius.xl,
    minWidth: 130,
    alignItems: "center",
    justifyContent: "center",
    ...effects.whiteGlow,
  },
  multiButton: {
    backgroundColor: colors.cyan,
    paddingHorizontal: spacing.xxxl,
    paddingVertical: spacing.lg,
    borderRadius: radius.xl,
    minWidth: 130,
    alignItems: "center",
    justifyContent: "center",
    ...effects.cyanGlow,
  },
  startButtonText: {
    color: "#000000",
    fontSize: typography.sizes.xl,
    fontWeight: typography.weights.bold,
    fontFamily: typography.game,
  },
  multiButtonText: {
    color: "#000000",
    fontSize: typography.sizes.xl,
    fontWeight: typography.weights.bold,
    fontFamily: typography.game,
  },
  buttonRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  inputLabel: {
    color: colors.cyan,
    fontFamily: typography.game,
    fontSize: typography.sizes.sm,
    fontWeight: typography.weights.bold,
    marginBottom: spacing.sm,
    textAlign: "center",
    textTransform: "uppercase",
  },
  input: {
    backgroundColor: colors.surface,
    color: colors.white,
    padding: 15,
    borderRadius: radius.lg,
    width: 260,
    marginBottom: spacing.xl,
    fontFamily: typography.game,
    textAlign: "center",
    fontSize: typography.sizes.lg,
    borderWidth: 1,
    borderColor: "rgba(0, 240, 255, 0.2)",
  },
  backButton: {
    position: "absolute",
    top: 50,
    left: 20,
    zIndex: 100,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    borderRadius: radius.round,
    borderWidth: 1,
    borderColor: colors.cyan,
    backgroundColor: "rgba(0, 240, 255, 0.15)",
    minHeight: 44,
    minWidth: 80,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  backButtonText: {
    color: colors.cyan,
    fontSize: typography.sizes.sm,
    fontFamily: typography.game,
    fontWeight: typography.weights.bold,
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.overlay,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
  },
  overlayText: {
    color: colors.white,
    fontSize: typography.sizes.xxl,
    fontFamily: typography.game,
  },
});
